device: "Dev1"

digital_outputs:     # DO used to *drive* Teensy/Shift Registers/Triggers
  OLFACTOMETER_LEFT_S0:        "Dev1/port0/line0"
  OLFACTOMETER_LEFT_S1:        "Dev1/port0/line1"
  OLFACTOMETER_LEFT_S2:        "Dev1/port0/line2"
  SWITCHVALVE_LEFT_S:          "Dev1/port0/line3"
  OLFACTOMETER_RIGHT_S0:       "Dev1/port0/line4"
  OLFACTOMETER_RIGHT_S1:       "Dev1/port0/line5"
  OLFACTOMETER_RIGHT_S2:       "Dev1/port0/line6"
  SWITCHVALVE_RIGHT_S:         "Dev1/port0/line7"
  RCK_OLFACTOMETER_LEFT:       "Dev1/port0/line8"
  RCK_SWITCHVALVE_LEFT:        "Dev1/port0/line9"
  RCK_OLFACTOMETER_RIGHT:      "Dev1/port0/line10"
  RCK_SWITCHVALVE_RIGHT:       "Dev1/port0/line11"
  TRIG_MICRO:                  "Dev1/port0/line12"
  TRIG_CAMERA:                 "Dev1/port0/line13"
  GLOBAL_LOAD_REQ:             "Dev1/port0/line14"
  OLFACTOMETER_LEFT_LOAD_REQ:  "Dev1/port0/line19"
  OLFACTOMETER_RIGHT_LOAD_REQ: "Dev1/port0/line20"
  SWITCHVALVE_LEFT_LOAD_REQ:   "Dev1/port0/line21"
  SWITCHVALVE_RIGHT_LOAD_REQ:  "Dev1/port0/line22"

digital_inputs:
  READY_OLFACTOMETER_LEFT:       "Dev1/port0/line15"
  READY_SWITCHVALVE_LEFT:        "Dev1/port0/line16"
  READY_OLFACTOMETER_RIGHT:      "Dev1/port0/line17"
  READY_SWITCHVALVE_RIGHT:       "Dev1/port0/line18"
  

analog_outputs:     # MFC Control
  mfc.air_left_setpoint:   "Dev1/ao0"
  mfc.air_right_setpoint:  "Dev1/ao1"
  mfc.odor_left_setpoint:  "Dev1/ao2"
  mfc.odor_right_setpoint: "Dev1/ao3"

analog_inputs:     # MFC Feedback
  mfc.air_left_flowrate:   "Dev1/ai0"
  mfc.air_right_flowrate:  "Dev1/ai1"
  mfc.odor_left_flowrate:  "Dev1/ai2"
  mfc.odor_right_flowrate: "Dev1/ai3"
