device: "Dev1"

digital_outputs:     # DO used to *drive* Teensy/Shift Registers/Triggers
  A_S0:        "Dev1/port0/line0"
  A_S1:        "Dev1/port0/line1"
  A_S2:        "Dev1/port0/line2"
  A_LOAD_REQ:  "Dev1/port0/line3"
  RCK_A:       "Dev1/port0/line4"
  B_S0:        "Dev1/port0/line5"
  B_S1:        "Dev1/port0/line6"
  B_S2:        "Dev1/port0/line7"
  B_LOAD_REQ:  "Dev1/port0/line8"
  RCK_B:       "Dev1/port0/line9"
  C_S:         "Dev1/port0/line10"
  C_LOAD_REQ:  "Dev1/port0/line11"
  RCK_C:       "Dev1/port0/line12"
  D_S:         "Dev1/port0/line13"
  D_LOAD_REQ:  "Dev1/port0/line14"
  RCK_D:       "Dev1/port0/line15"
  TRIG_MICRO:  "Dev1/port0/line16"
  TRIG_CAMERA: "Dev1/port0/line17"

analog_outputs:     # MFC Control
  mfc.air_left_setpoint:   "Dev1/ao0"
  mfc.air_right_setpoint:  "Dev1/ao1"
  mfc.odor_left_setpoint:  "Dev1/ao2"
  mfc.odor_right_setpoint: "Dev1/ao3"

analog_inputs:     # MFC Feedback
  mfc.air_left_flowrate:   "Dev1/ai0"
  mfc.air_right_flowrate:  "Dev1/ai1"
  mfc.odor_left_flowrate:  "Dev1/ai2"
  mfc.odor_right_flowrate: "Dev1/ai3"
